name: quizapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.15.2
  cloud_firestore: ^5.6.12
  cupertino_icons: ^1.0.8
  video_player: ^2.9.1
  flutter_launcher_icons: ^0.14.4
  audioplayers: ^5.2.0
  vibration: ^2.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# ðŸ‘‡ ESTA SECCIÃ“N VA FUERA DE LAS DEPENDENCIAS
flutter_icons:
  android: true
  ios: true
  image_path: "assets/imagenes_general/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/imagenes_general/
    - assets/gato/
    - assets/conejo/
    - assets/perro/
    - assets/musica/
